# 把网页里所有需要朗读的内容用 Azure 生成 mp3，放在 audio 文件夹，并写出 audio/manifest.js 清单。
# 已经生成过的不会重复生成；内容删掉以后，多余的 mp3 也会被清理。
# 用法：powershell -ExecutionPolicy Bypass -File tools\make-audio.ps1
. "$PSScriptRoot\azure-tts.ps1"
$root = Split-Path $PSScriptRoot -Parent
$audio = Join-Path $root 'audio'
New-Item -ItemType Directory -Force $audio | Out-Null

$ContentVoice = 'en-US-AvaMultilingualNeural'   # 学习内容：Ava，正常语速
$PraiseVoice = 'en-US-JennyNeural'              # 夸奖：Jenny，兴奋的语气
$PraiseStyle = 'excited'

# 文件名 = 文本的 FNV-1a 32 位哈希（和网页里的算法完全一样）
function Get-Fnv([string]$s) {
  [uint64]$h = 2166136261
  foreach ($c in $s.ToCharArray()) { $h = $h -bxor [uint64][int]$c; $h = ($h * 16777619) % 4294967296 }
  '{0:x8}' -f $h
}

# ---------- 从 index.html 里找出所有会被读出来的文本 ----------
$html = [IO.File]::ReadAllText((Join-Path $root 'index.html'), [Text.Encoding]::UTF8)
$lines = $html -split "`r?`n"
$start = [Array]::FindIndex($lines, [Predicate[string]] { param($l) $l.StartsWith('const LEVELS=[') })
$level = -1
$content = New-Object 'System.Collections.Generic.HashSet[string]'
function Clean([string]$t) {
  $t = $t.Replace('*', '')
  if ($t -match '\[([^\]]+)\]') { $t = $t.Replace($Matches[0], $Matches[1].Split('/')[0]) }
  $t.Trim()
}
for ($i = $start + 1; $i -lt $lines.Count; $i++) {
  $l = $lines[$i] -replace '`[),]*$', ''   # 去掉每个单元最后一行末尾的 ) 或 ,
  if ($l -eq '];') { break }
  if ($l -match "^\{id:'") { $level++; continue }
  $p = $l.Split('|')
  if ($p.Count -eq 3) {                       # 学习内容：英文 | 图片 | 中文
    $t = Clean $p[0]
    [void]$content.Add($t)
    $words = $t -split '\s+'
    if ($level -ge 2 -and $words.Count -ge 3) { foreach ($w in $words) { $w = $w -replace '[.,!?]+$', ''; if ($w) { [void]$content.Add($w) } } }   # 连词成句点单词时读单词
  } elseif ($p.Count -eq 4) {                 # 小测验：问题 | 中文 | 答案 | 错误选项
    [void]$content.Add($p[0].Trim())
    if ($level -ge 1) { [void]$content.Add($p[2].Trim()); foreach ($w in $p[3].Split(';')) { [void]$content.Add($w.Trim()) } }
  }
}
$praise = New-Object 'System.Collections.Generic.HashSet[string]'
if ($html -match "const PRAISE=\[([^\]]+)\]") { foreach ($m in [regex]::Matches($Matches[1], "'([^']+)'")) { [void]$praise.Add($m.Groups[1].Value) } }
foreach ($t in @('Level up! You are amazing!', 'Perfect! You are amazing!', 'Great job!', 'Well done!')) { [void]$praise.Add($t) }

# ---------- 生成 ----------
$want = @{}
foreach ($t in $content) { $want[(Get-Fnv $t)] = @{ text = $t; voice = $ContentVoice; style = '' } }
foreach ($t in $praise) { $want['p' + (Get-Fnv $t)] = @{ text = $t; voice = $PraiseVoice; style = $PraiseStyle } }
Write-Host "texts: content $($content.Count), praise $($praise.Count)"

$todo = @($want.Keys | Where-Object { -not (Test-Path (Join-Path $audio "$_.mp3")) })
Write-Host "to generate: $($todo.Count)"
$n = 0; $failed = 0
foreach ($k in $todo) {
  $w = $want[$k]; $n++
  $ok = Invoke-Tts -Text $w.text -Voice $w.voice -Style $w.style -Rate '0%' -OutFile (Join-Path $audio "$k.mp3")
  if (-not $ok) { $failed++; Remove-Item (Join-Path $audio "$k.mp3") -ErrorAction SilentlyContinue }
  if ($n % 50 -eq 0) { Write-Host "  $n / $($todo.Count)" }
}

# 删掉不再需要的旧文件
Get-ChildItem $audio -Filter '*.mp3' | Where-Object { -not $want.ContainsKey($_.BaseName) } | ForEach-Object { Remove-Item $_.FullName; Write-Host "  removed $($_.Name)" }

# 清单：网页据此判断哪些句子有录音
$have = @(Get-ChildItem $audio -Filter '*.mp3' | ForEach-Object { $_.BaseName } | Sort-Object)
$js = "// generated by tools/make-audio.ps1 - $($have.Count) clips`nwindow.AUDIO=new Set(" + ('["' + ($have -join '","') + '"]') + ");`n"
[IO.File]::WriteAllText((Join-Path $audio 'manifest.js'), $js, (New-Object Text.UTF8Encoding($false)))
$size = (Get-ChildItem $audio -Filter '*.mp3' | Measure-Object Length -Sum).Sum
Write-Host ("done: {0} clips, {1:N1} MB, failed {2}" -f $have.Count, ($size / 1MB), $failed)
